name: Docker Image CI
env:
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  DOCKER_REPONAME:  "capstone-bcrypt" 

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'app/**'
      - '.github/**'

jobs:
  docker-build-bcrypt:
    name: Docker build bcrypt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: |
        docker build . \
        --file Dockerfile \
        --tag $DOCKER_USERNAME/$DOCKER_REPONAME:${GITHUB_SHA::6}
    - name: Login to Dockerhub
      run: | 
        echo $DOCKER_PASSWORD | \
        docker login https://index.docker.io/v1/ \
        --username $DOCKER_USERNAME --password-stdin
    - name: Push the Docker image
      run: |
        docker push \
        $DOCKER_USERNAME/$DOCKER_REPONAME:${GITHUB_SHA::6}
    
